// <auto-generated />
namespace DiscountNotifier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CorrectedDiscount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrectedDiscount));
        
        string IMigrationMetadata.Id
        {
            get { return "201711210122109_CorrectedDiscount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
