#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iBeaconPracticeApp.Resource", IsApplication=true)]

namespace iBeaconPracticeApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnLogin = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btnRegister = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int imageView = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout3 = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int listView = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int tvConfirmPassword = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int tvEmail = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int tvFullname = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int tvPassword = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int tvUsername = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int tv_discount = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int tv_name = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int tv_price = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int tv_region = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int product_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Hello = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int error_no_bluetooth_enabled = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int error_no_bluetooth_le = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_no_location_permission = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int requesting_location_access = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int requesting_location_access_cancel = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int requesting_location_access_ok = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int requesting_location_access_rationale = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int requesting_location_permission = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int requesting_location_permission_rationale = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Transparent = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
