// <auto-generated />
namespace Homework_04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SurveyAddProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SurveyAddProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161420369_Survey-Add-Properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
